package view;

import controller.Conexao;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import report.Relatorio;

/*
 * @author Gustavo
 */

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        
        this.setTitle("Minha Oficina");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    //Método para abrir Formulário
    private void abrirForm(JInternalFrame f){
        if (areaTrabalho.getAllFrames().length == 0){
            Dimension d = areaTrabalho.getSize();
            areaTrabalho.add(f);
            f.setLocation( (d.width-f.getSize().width)/2,
                           (d.height-f.getSize().height)/2);
            f.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuCadastroPeca = new javax.swing.JMenuItem();
        menuCadastroFornecedor = new javax.swing.JMenuItem();
        menuPesquisa = new javax.swing.JMenu();
        menuPesquisaCliente = new javax.swing.JMenuItem();
        menuPesquisaPeca = new javax.swing.JMenuItem();
        menuPesquisaFornecedor = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelatorioCliente = new javax.swing.JMenuItem();
        menuRelatorioPeca = new javax.swing.JMenuItem();
        menuRelatorioFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");

        menuCadastroCliente.setText("Cliente");
        menuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroCliente);

        menuCadastroPeca.setText("Peça");
        menuCadastroPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPecaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroPeca);

        menuCadastroFornecedor.setText("Fornecedor");
        menuCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFornecedorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroFornecedor);

        barraMenu.add(menuCadastro);

        menuPesquisa.setText("Pesquisa");

        menuPesquisaCliente.setText("Cliente");
        menuPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaClienteActionPerformed(evt);
            }
        });
        menuPesquisa.add(menuPesquisaCliente);

        menuPesquisaPeca.setText("Peça");
        menuPesquisaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaPecaActionPerformed(evt);
            }
        });
        menuPesquisa.add(menuPesquisaPeca);

        menuPesquisaFornecedor.setText("Fornecedor");
        menuPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaFornecedorActionPerformed(evt);
            }
        });
        menuPesquisa.add(menuPesquisaFornecedor);

        barraMenu.add(menuPesquisa);

        menuRelatorio.setText("Relatório");

        menuRelatorioCliente.setText("Cliente");
        menuRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioClienteActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioCliente);

        menuRelatorioPeca.setText("Peça");
        menuRelatorioPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioPecaActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioPeca);

        menuRelatorioFornecedor.setText("Fornecedor");
        menuRelatorioFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioFornecedorActionPerformed(evt);
            }
        });
        menuRelatorio.add(menuRelatorioFornecedor);

        barraMenu.add(menuRelatorio);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(areaTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClienteActionPerformed
        abrirForm( new FormCadastroCliente() );
    }//GEN-LAST:event_menuCadastroClienteActionPerformed

    private void menuCadastroPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPecaActionPerformed
        abrirForm( new FormCadastroPeca() );
    }//GEN-LAST:event_menuCadastroPecaActionPerformed

    private void menuCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFornecedorActionPerformed
        abrirForm( new FormCadastroFornecedor() );
    }//GEN-LAST:event_menuCadastroFornecedorActionPerformed

    private void menuPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaClienteActionPerformed
        abrirForm( new FormPesquisaCliente() );
    }//GEN-LAST:event_menuPesquisaClienteActionPerformed

    private void menuPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaFornecedorActionPerformed
        abrirForm( new FormPesquisaFornecedor() );
    }//GEN-LAST:event_menuPesquisaFornecedorActionPerformed

    private void menuPesquisaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaPecaActionPerformed
        abrirForm( new FormPesquisaPeca() );
    }//GEN-LAST:event_menuPesquisaPecaActionPerformed

    private void menuRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioClienteActionPerformed
        new Relatorio().exibir(Conexao.conectar(),"relatorio_clientes.jrxml");
    }//GEN-LAST:event_menuRelatorioClienteActionPerformed

    private void menuRelatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioFornecedorActionPerformed
        new Relatorio().exibir(Conexao.conectar(),"relatorio_fornecedores.jrxml");
    }//GEN-LAST:event_menuRelatorioFornecedorActionPerformed

    private void menuRelatorioPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioPecaActionPerformed
        new Relatorio().exibir(Conexao.conectar(),"relatorio_pecas.jrxml");
    }//GEN-LAST:event_menuRelatorioPecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroCliente;
    private javax.swing.JMenuItem menuCadastroFornecedor;
    private javax.swing.JMenuItem menuCadastroPeca;
    private javax.swing.JMenu menuPesquisa;
    private javax.swing.JMenuItem menuPesquisaCliente;
    private javax.swing.JMenuItem menuPesquisaFornecedor;
    private javax.swing.JMenuItem menuPesquisaPeca;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuRelatorioCliente;
    private javax.swing.JMenuItem menuRelatorioFornecedor;
    private javax.swing.JMenuItem menuRelatorioPeca;
    // End of variables declaration//GEN-END:variables
}
